### ISSUE TITLE
(401) unauthorized from websocketclient.connectasync in speechclient.cs

### ISSUE THREAD

**Issue by jhealy** [MicrosoftTranslator/SpeechTranslator#11]
I'm using the stock Speech Translator C# sample from https://github.com/MicrosoftTranslator/SpeechTranslator .

I've entered my keys from azure correctly.

speechclient.cs failes at line 147 with await websocketclient.connectasync( clientwsuri,, cancellationtoken)

clientWsUri {wss://dev.microsofttranslator.com/speech/translate?from=en-US&to=sv&voice=sv-SE-Karin&features=TextToSpeech,Partial&profanity=Strict&flight=experimental&api-version=1.0} System.Uri

When I trace through various auth tokens look valid but the line below seems to kick up unauth

Log output - long run is cause I was stepping through it.

05/16/2017 22:17:07.55 E: Unable to connect: cid='4D530666', elapsedMs='170056'. 
Unable to connect to the remote server 
The remote server returned an error: (401) Unauthorized.

Thanks...

serviceurl = +  ServiceUrl {https://api.cognitive.microsoft.com/sts/v1.0/issueToken} System.Uri

token source has sub id:

? tokenSource

{Microsoft.Translator.API.AzureAuthToken}

RequestStatusCode: InternalServerError

    SubscriptionKey: "..................389803"

    storedTokenTime: {1/1/0001 12:00:00 AM}

    storedTokenValue: ""

{Microsoft.MT.Api.TestUtils.SpeechTranslateClientOptions}

    AuthHeaderKey: "Authorization"

    AuthHeaderValue: ""

    ClientAppId: {ea66703d-90a8-436b-9bd6-7a2707a2ad99}

    CorrelationId: "7147E079"

    Experimental: true

    Features: "TextToSpeech,Partial"

    Hostname: "dev.microsofttranslator.com"

    Profanity: "Strict"

    TranslateFrom: "en-US"

    TranslateTo: "sv"

    Voice: "sv-SE-Karin"

**Comment by SychevIgor** [comment]
@chriswendt1 @anthonyaue @federiga @kellyaltom @cfedermann Colleguaes could you please help us with it?

**Comment by SychevIgor** [comment]
I have the same problem. My key successfully working with REST API, but not working with WebSockets

**Comment by michele-b** [comment]
@SychevIgor Some problem for me; the remote server returned (401) Unauthorized error

**Comment by chriswendt1** [comment]
Make sure you have a Translator Speech API key. The Translator Text API key won't work. 
Save the new key, exit and restart. The sample doesn't update dynamically.
