### ISSUE TITLE
Speech to Speech feature

### ISSUE THREAD

**Issue by saikrishna-2017** [MicrosoftTranslator/SpeechTranslator#17]
Hi I have gone through many documents and check out the code, speech to text is working fine but I cannot hear the translated speech.  Kindly let me know whether speech to speech is currently supported or not? For example I would like to hear back the response in  French when I speak in English.
If it supported then kindly let me know how to use this feature?

**Comment by kellyaltom** [comment]
Hi,


Add the TextToSpeech feature to the request. At the same time the translated text is returning as JSON you will be receiving data in chunks of audio.


http://docs.microsofttranslator.com/speech-translate.html

Cognitive Services - Microsoft Translator Speech API<http://docs.microsofttranslator.com/speech-translate.html>
docs.microsofttranslator.com
Documentation Microsoft Translator Speech API. Authentication Token API; Microsoft Translator Text API; Microsoft Translator Speech API

Kelly



________________________________

**Comment by saikrishna-2017** [comment]
Hi Kelly, 

Thanks for fast response.
I am able to run this sample code with out any issues, I can see the UI where I can select the input, log window etc. 
During the translation period I can hear only input audio and view the translated text but I cannot hear the translated audio, however I can see the sent audio file with the name (audiosent_somename.wav) but the audiotts_somename.wav are not generated.

Kindly let me know whether from this sample code can get the audiotts_name.wav files or not?
Thanks.

Sai.

**Comment by saikrishna-2017** [comment]
Hi Kelly,

I found the root cause, the following code is the issue (line 1145 to line 1156 of MainWindow.xaml.cs)
        private SpeechClient.Features GetFeatures()
        {
            SpeechClient.Features features =  SpeechClient.Features.TimingInfo;

            if (FeaturePartials.IsChecked.Value)
                features |= SpeechClient.Features.Partial;
            if (FeatureTTS.IsChecked.Value)
                features |= SpeechClient.Features.TextToSpeech;

            
            return features;
        }

This method always return TimingInfo even on UI if we select TTS or Partial or both , which further causes the wrong URI request for "features" parameter.

Kindly check on your side and let me know if my understanding is correct or not.
Thanks.

Sai.

**Comment by saikrishna-2017** [comment]
@kellyaltom 
Any update?

**Comment by rusrc** [comment]
To get partial text too just change enumeration Features as bellow:

 [Flags]
        public enum Features
        {
            TextToSpeech = 2,
            Partial = 4,
            TimingInfo = 8,
        }

**Comment by chriswendt1** [comment]
Thanks @rusrc.
Merged into main branch.
