### ISSUE TITLE
TTS Not working

### ISSUE THREAD

**Issue by robert4os** [MicrosoftTranslator/SpeechTranslator#18]
Translation works, but no speech/audio output is produced.

**Comment by robert4os** [comment]
The solution is described here: https://github.com/MicrosoftTranslator/SpeechTranslator/issues/14

**Comment by chriswendt1** [comment]
Fixed in 0.9.2. Two changes: By @marcominerva to fix the offset for TTS info, and to change the bitrate from 16K to 24K.
