### ISSUE TITLE
speech translator voice result is strange

### ISSUE THREAD

**Issue by sunt89** [MicrosoftTranslator/SpeechTranslator#20]
when i set the voice to female, but the voice returned is male, And the voice sound strange, it plays very slowly....

**Comment by chriswendt1** [comment]
Indeed. The voice returned is 24kHz, but the app expects 16kHz. Will need to adapt.

**Comment by sunt89** [comment]
@chriswendt1   Thank you very much, and i also find the problem, when i save as a audio file, it is ok, and the rate is 24kHz.   And now i solved the problem.

**Comment by chriswendt1** [comment]
Thanks for the note. Do you have coded up the fix that we could integrate into Speech Translator?

**Comment by sunt89** [comment]
@chriswendt1   I just new a waveformat, and set the playerTextToSpeechWaveProvider with new waveformat
`WaveFormat playerWaveFormat = new WaveFormat(24000, 16, 1);`
`playerTextToSpeechWaveProvider = new BufferedWaveProvider(playerWaveFormat);`
