### ISSUE TITLE
http://docs.microsofttranslator.com/speech-translate.html   is Invalid

### ISSUE THREAD

**Issue by hxcurtain** [MicrosoftTranslator/SpeechTranslator#22]
Your translation APi cannot be accessed normally. I was able to access it yesterday, but it cannot be accessed successfully today      [http://docs.microsofttranslator.com/speech-translate.html ](http://docs.microsofttranslator.com/speech-translate.html )

**Comment by kellyaltom** [comment]
You can find the docs at:

https://docs.microsoft.com/en-us/azure/cognitive-services/translator-speech/reference
[https://docs.microsoft.com/_themes/docs.theme/master/en-us/_themes/images/microsoft-header.png]<https://docs.microsoft.com/en-us/azure/cognitive-services/translator-speech/reference>

Microsoft Translator Speech API Reference - Cognitive ...<https://docs.microsoft.com/en-us/azure/cognitive-services/translator-speech/reference>
docs.microsoft.com
This service offers a streaming API to transcribe conversational speech from one language into text of another language. The API also integrates text-to-speech capabilities to speak the translated text back. Microsoft Translator Speech API enables scenarios like real-time translation of ...




________________________________

**Comment by hxcurtain** [comment]
Thank You！

**Comment by chriswendt1** [comment]
README is fixed also.
