### ISSUE TITLE
(offline) Translator for Windows 

### ISSUE THREAD

**Issue by JimSEOW** [MicrosoftTranslator/SpeechTranslator#3]
Q1
Is [translator for windows](https://www.microsoft.com/en-us/translator/windows.aspx) (offline) open source?

Q2
Where could we find information (preferably github) on how to do offline translation the same way as Translator for Windows (UWP) mobile phone?

**Comment by kellyaltom** [comment]
Hi Jim,


Q1 - Sorry translator for windows is not open sourced


Q2 - That is not something we offer outside of Translator for Windows.


Kelly


________________________________
