### ISSUE TITLE
[Error] Unable to connect to Remote Server

### ISSUE THREAD

**Issue by kurayahi** [MicrosoftTranslator/SpeechTranslator#4]
Sorry, this may be novice point.
Speech Translator doesn't work by Unable to connect error (401). Some configuration may be wrong.

I modified app.config with specifying ClientId and ClientSecret. 
I tied two cases. However, neither case doesn't work.
#1 : Specify primary account key and client ID of my account (https://datamarket.azure.com/account).
#2 : Specify client ID and client secret of my application (https://datamarket.azure.com/developer/applications/)

```
      <setting name="ClientID" serializeAs="String">
            <value/
     </setting>
        <setting name="ClientSecret" serializeAs="String">
          <value/>
       </setting>
```

Could you please help on this?

**Comment by chriswendt1** [comment]
Be sure to subscribe to "Microsoft Translator - Speech Translation". There is also a "Microsoft Translator - Text Translation" subscription. It'll work only with the Speech Translation subscription.
This https://datamarket.azure.com/developer/applications/ is the correct place to define your credentials. Should work.

**Comment by gratitudepod** [comment]
I am having the same issue. I created ClientID and Secret key at https://datamarket.azure.com/developer/applications/

I ran the SpeechTranlator App, went to the setting and entered clientID and secret key that I got from the above URL. When I clicked on 'Start' button, I got this error:

11/06/2016 10:56:12.07 E: Unable to connect: cid='8B180E40', elapsedMs='841'.
Unable to connect to the remote server.
The remote server returned and error: (401) Unauthorized.

**Comment by gratitudepod** [comment]
Good news I got it to work. Here's how I did it.

1) Follow Step Three in this URL https://translatorbusiness.uservoice.com/knowledgebase/articles/1078534-microsoft-translator-on-azure

3.     Add Microsoft Translator subscription to your Azure account.

Select the ﻿+ New ﻿option.
Select ﻿Intelligence﻿ from the list of services.
Select ﻿Cognitive Services APIs﻿.
Select the ﻿API Type﻿ option.
﻿Select either ﻿Text Translation ﻿or ﻿Speech Translation
 ﻿In the ﻿Pricing Tier﻿ section, select the pricing tier that fits your needs.
Fill out the rest of the form, and press the ﻿Create﻿ button
You are now subscribed to Microsoft Translator!

2) Then go to https://datamarket.azure.com/developer/applications/ to Register your new App:

3) when I ran SpeechTranslator app, I enter the clientID and secret key created in Step 2 above and it worked.

Hope this helps.

**Comment by shaneroy** [comment]
After following all these steps I am still getting the (401) unauthorized message. 

I signed up for the free level of translator through the Azure portal. I set up the application in the DataMarket (it seems like they are linked through my MSDN account??).

Is there anything from the Speech Cognitive Service Account that needs to be input in the DataMarket account?

What am I overlooking?

**Comment by chriswendt1** [comment]
Hi shaneroy, I merged the AzureAuth branch into master, so AzureAuth via the Azure Portal is all you see now. Enter your key for your Microsoft Translator - Speech translation subscription, and it should work.
