### ISSUE TITLE
Tried to translate long audio files

### ISSUE THREAD

**Issue by signkabob** [MicrosoftTranslator/SpeechTranslator#7]
As someone who's unfamiliar with audio programming, I've been struggling to get the translation to work with long audio files. I have adjusted the WaveFormat to appropriately match these files (usually 48000 Hz, 16-bits, and mono), but the sound stream I've been getting was choppy. Is there other method or time duration that I have overlooked?

**Comment by kellyaltom** [comment]
Hi,


Your sample rate is too high, 48k will cause problems. 16000 is the best sample rate to use. The other settings are fine.


Kelly


________________________________

**Comment by signkabob** [comment]
Thanks for the response! 

So I suppose the best way to translate the long audio file is to split it, reducing the sample rate to 16000 hz, and then run one by one in succession?

**Comment by kellyaltom** [comment]
There are a few software packages available that will do the conversion. This one is free. http://www.nch.com.au/switch/


There are some github repos that have the code to convert files.


Not sure what you mean by split the file.


Kelly

Convert Audio Files To/From All Audio Formats with Switch<http://www.nch.com.au/switch/>
www.nch.com.au
It's easy to convert to Mp3, wav, wma, flac, ogg and more this #1 rated audio file converter. Convert a single audio file, a playlist or a large batch of files.







________________________________

**Comment by signkabob** [comment]
Thanks, I will try your suggestions!
