### ISSUE TITLE
Getting a language list sure takes a while

### ISSUE THREAD

**Issue by signkabob** [MicrosoftTranslator/SpeechTranslator#9]
I don't know if it's a bug or not, but even leaving the program running for hours from scratch still haven't gotten a full language list. I tried to input and save the subscription key but it crashed the program. Just thought you should know.

**Comment by kellyaltom** [comment]
Getting a list of languages does not require a key. You can try it out at:


http://docs.microsofttranslator.com/languages.html


It comes back very quickly. Is this the method you are trying?

Cognitive Services - Supported Languages<http://docs.microsofttranslator.com/languages.html>
docs.microsofttranslator.com
403 : http://docs.microsofttranslator.com/openapi/languages-1.0.json. Contact Us; Privacy & Cookies; Terms of Use; Developer Code of Conduct; Trademarks





________________________________

**Comment by signkabob** [comment]
My apology. I realize I inputted my subscription id instead of the subscription key. The origin of my misunderstandings was the message "Getting language list from..." rather than "Invalid credentials. Please enter your account settings." I'll be appreciated if that'll be twerked. 

Noted I ran the program after the Azure migration update.
